### ISSUE TITLE
Exception when starting

### ISSUE THREAD

**Issue by rhuss** [fabric8io/docker-gerrit#8]
When using the current Vagrantfile with the current release of fabric8, the gerrit pod constantly restarts with this log

```
[vagrant@vagrant ~]$ oc logs gerrit-0uljx
>> .gerrit-configured doesn't exist. We will start gerrit to generate it
Exception in thread "main" java.io.IOException: Is a directory
    at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
    at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
    at sun.nio.ch.IOUtil.read(IOUtil.java:197)
    at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:149)
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
    at java.nio.file.Files.read(Files.java:2934)
    at java.nio.file.Files.readAllBytes(Files.java:2987)
    at com.googlesource.gerrit.plugins.AddUser.createSshKey(AddUser.java:335)
    at com.googlesource.gerrit.plugins.AddUser.readSshKey(AddUser.java:324)
    at com.googlesource.gerrit.plugins.AddUser.update(AddUser.java:248)
    at com.googlesource.gerrit.plugins.AddUser.postRun(AddUser.java:117)
    at com.google.gerrit.pgm.init.InitPlugins.postInitPlugins(InitPlugins.java:166)
    at com.google.gerrit.pgm.init.InitPlugins.postRun(InitPlugins.java:99)
    at com.google.gerrit.pgm.init.SitePathInitializer.postRun(SitePathInitializer.java:129)
    at com.google.gerrit.pgm.init.BaseInit.run(BaseInit.java:122)
    at com.google.gerrit.pgm.util.AbstractProgram.main(AbstractProgram.java:64)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.gerrit.launcher.GerritLauncher.invokeProgram(GerritLauncher.java:166)
    at com.google.gerrit.launcher.GerritLauncher.mainImpl(GerritLauncher.java:93)
    at com.google.gerrit.launcher.GerritLauncher.main(GerritLauncher.java:50)
    at Main.main(Main.java:25)
```

**Comment by rhuss** [comment]
Its the image `docker.io/fabric8/gerrit:latest` (0c092226fcad)
